// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/ONSdigital/dp-s3"
	"github.com/ONSdigital/florence/upload"
	"sync"
)

var (
	lockS3ClientMockCheckPartUploaded sync.RWMutex
	lockS3ClientMockUploadPart        sync.RWMutex
	lockS3ClientMockUploadPartWithPsk sync.RWMutex
)

// Ensure, that S3ClientMock does implement upload.S3Client.
// If this is not the case, regenerate this file with moq.
var _ upload.S3Client = &S3ClientMock{}

// S3ClientMock is a mock implementation of upload.S3Client.
//
//     func TestSomethingThatUsesS3Client(t *testing.T) {
//
//         // make and configure a mocked upload.S3Client
//         mockedS3Client := &S3ClientMock{
//             CheckPartUploadedFunc: func(ctx context.Context, req *s3client.UploadPartRequest) (bool, error) {
// 	               panic("mock out the CheckPartUploaded method")
//             },
//             UploadPartFunc: func(ctx context.Context, req *s3client.UploadPartRequest, payload []byte) error {
// 	               panic("mock out the UploadPart method")
//             },
//             UploadPartWithPskFunc: func(ctx context.Context, req *s3client.UploadPartRequest, payload []byte, psk []byte) error {
// 	               panic("mock out the UploadPartWithPsk method")
//             },
//         }
//
//         // use mockedS3Client in code that requires upload.S3Client
//         // and then make assertions.
//
//     }
type S3ClientMock struct {
	// CheckPartUploadedFunc mocks the CheckPartUploaded method.
	CheckPartUploadedFunc func(ctx context.Context, req *s3client.UploadPartRequest) (bool, error)

	// UploadPartFunc mocks the UploadPart method.
	UploadPartFunc func(ctx context.Context, req *s3client.UploadPartRequest, payload []byte) error

	// UploadPartWithPskFunc mocks the UploadPartWithPsk method.
	UploadPartWithPskFunc func(ctx context.Context, req *s3client.UploadPartRequest, payload []byte, psk []byte) error

	// calls tracks calls to the methods.
	calls struct {
		// CheckPartUploaded holds details about calls to the CheckPartUploaded method.
		CheckPartUploaded []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req *s3client.UploadPartRequest
		}
		// UploadPart holds details about calls to the UploadPart method.
		UploadPart []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req *s3client.UploadPartRequest
			// Payload is the payload argument value.
			Payload []byte
		}
		// UploadPartWithPsk holds details about calls to the UploadPartWithPsk method.
		UploadPartWithPsk []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req *s3client.UploadPartRequest
			// Payload is the payload argument value.
			Payload []byte
			// Psk is the psk argument value.
			Psk []byte
		}
	}
}

// CheckPartUploaded calls CheckPartUploadedFunc.
func (mock *S3ClientMock) CheckPartUploaded(ctx context.Context, req *s3client.UploadPartRequest) (bool, error) {
	if mock.CheckPartUploadedFunc == nil {
		panic("S3ClientMock.CheckPartUploadedFunc: method is nil but S3Client.CheckPartUploaded was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req *s3client.UploadPartRequest
	}{
		Ctx: ctx,
		Req: req,
	}
	lockS3ClientMockCheckPartUploaded.Lock()
	mock.calls.CheckPartUploaded = append(mock.calls.CheckPartUploaded, callInfo)
	lockS3ClientMockCheckPartUploaded.Unlock()
	return mock.CheckPartUploadedFunc(ctx, req)
}

// CheckPartUploadedCalls gets all the calls that were made to CheckPartUploaded.
// Check the length with:
//     len(mockedS3Client.CheckPartUploadedCalls())
func (mock *S3ClientMock) CheckPartUploadedCalls() []struct {
	Ctx context.Context
	Req *s3client.UploadPartRequest
} {
	var calls []struct {
		Ctx context.Context
		Req *s3client.UploadPartRequest
	}
	lockS3ClientMockCheckPartUploaded.RLock()
	calls = mock.calls.CheckPartUploaded
	lockS3ClientMockCheckPartUploaded.RUnlock()
	return calls
}

// UploadPart calls UploadPartFunc.
func (mock *S3ClientMock) UploadPart(ctx context.Context, req *s3client.UploadPartRequest, payload []byte) error {
	if mock.UploadPartFunc == nil {
		panic("S3ClientMock.UploadPartFunc: method is nil but S3Client.UploadPart was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Req     *s3client.UploadPartRequest
		Payload []byte
	}{
		Ctx:     ctx,
		Req:     req,
		Payload: payload,
	}
	lockS3ClientMockUploadPart.Lock()
	mock.calls.UploadPart = append(mock.calls.UploadPart, callInfo)
	lockS3ClientMockUploadPart.Unlock()
	return mock.UploadPartFunc(ctx, req, payload)
}

// UploadPartCalls gets all the calls that were made to UploadPart.
// Check the length with:
//     len(mockedS3Client.UploadPartCalls())
func (mock *S3ClientMock) UploadPartCalls() []struct {
	Ctx     context.Context
	Req     *s3client.UploadPartRequest
	Payload []byte
} {
	var calls []struct {
		Ctx     context.Context
		Req     *s3client.UploadPartRequest
		Payload []byte
	}
	lockS3ClientMockUploadPart.RLock()
	calls = mock.calls.UploadPart
	lockS3ClientMockUploadPart.RUnlock()
	return calls
}

// UploadPartWithPsk calls UploadPartWithPskFunc.
func (mock *S3ClientMock) UploadPartWithPsk(ctx context.Context, req *s3client.UploadPartRequest, payload []byte, psk []byte) error {
	if mock.UploadPartWithPskFunc == nil {
		panic("S3ClientMock.UploadPartWithPskFunc: method is nil but S3Client.UploadPartWithPsk was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Req     *s3client.UploadPartRequest
		Payload []byte
		Psk     []byte
	}{
		Ctx:     ctx,
		Req:     req,
		Payload: payload,
		Psk:     psk,
	}
	lockS3ClientMockUploadPartWithPsk.Lock()
	mock.calls.UploadPartWithPsk = append(mock.calls.UploadPartWithPsk, callInfo)
	lockS3ClientMockUploadPartWithPsk.Unlock()
	return mock.UploadPartWithPskFunc(ctx, req, payload, psk)
}

// UploadPartWithPskCalls gets all the calls that were made to UploadPartWithPsk.
// Check the length with:
//     len(mockedS3Client.UploadPartWithPskCalls())
func (mock *S3ClientMock) UploadPartWithPskCalls() []struct {
	Ctx     context.Context
	Req     *s3client.UploadPartRequest
	Payload []byte
	Psk     []byte
} {
	var calls []struct {
		Ctx     context.Context
		Req     *s3client.UploadPartRequest
		Payload []byte
		Psk     []byte
	}
	lockS3ClientMockUploadPartWithPsk.RLock()
	calls = mock.calls.UploadPartWithPsk
	lockS3ClientMockUploadPartWithPsk.RUnlock()
	return calls
}
