export const LOAD_GROUP_FAILURE = "LOAD_GROUP_FAILURE";
export const LOAD_GROUP_SUCCESS = "LOAD_GROUP_SUCCESS";
export const LOAD_GROUP_PROGRESS = "LOAD_GROUP_PROGRESS";

export const LOAD_GROUP_MEMBERS_SUCCESS = "LOAD_GROUP_MEMBERS_SUCCESS";
export const LOAD_GROUP_MEMBERS_FAILURE = "LOAD_GROUP_MEMBERS_FAILURE";
export const LOAD_GROUP_MEMBERS_PROGRESS = "LOAD_GROUP_MEMBERS_PROGRESS";

export const UPDATE_GROUP_FAILURE = "UPDATE_GROUP_FAILURE";
export const UPDATE_GROUP_SUCCESS = "UPDATE_GROUP_SUCCESS";
export const UPDATE_GROUP_PROGRESS = "UPDATE_GROUP_PROGRESS";

export const DELETE_GROUP_FAILURE = "DELETE_GROUP_FAILURE";
export const DELETE_GROUP_SUCCESS = "DELETE_GROUP_SUCCESS";
export const DELETE_GROUP_PROGRESS = "DELETE_GROUP_PROGRESS";

export const LOAD_GROUPS_FAILURE = "LOAD_GROUPS_FAILURE";
export const LOAD_GROUPS_SUCCESS = "LOAD_GROUPS_SUCCESS";
export const LOAD_GROUPS_PROGRESS = "LOAD_GROUPS_PROGRESS";

export const UPDATE_GROUP_MEMBERS_SUCCESS = "UPDATE_GROUP_MEMBERS_SUCCESS";
