# This file was inspired by the golangci-lint one:
# https://github.com/golangci/golangci-lint/blob/master/.golangci.yml
run:
  # number of operating system threads that can execute golangci-lint simultaneously
  concurrency: 4

  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 5m
linters-settings:
  govet:
    shadow: true
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 20
  gocognit:
    min-complexity: 40
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: UK
  lll:
    line-length: 140
  gofmt:
    simplify: false
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - wrapperFunc
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - octalLiteral
      - hugeParam
  revive:
    rules:
      # disabled as parameter names are useful for context even when unused, especially in interface implementations
      - name: unused-parameter
        severity: warning
        disabled: true
    include:
      - "**/*_test.go" # Specify test files to include
  funlen:
  # lines: 100
  # statements: 100

linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - dogsled
    - errcheck
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - revive
    - gosec
    - gosimple
    - govet
    - ineffassign
    - nakedret
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unused
    - whitespace
    - gocognit
    - prealloc

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
    # Allow dot import in test files for goconvey
    - path: _test.go
      text: "dot-imports"
      linters:
        - revive
      source: "github.com/smartystreets/goconvey/convey"
  new: false
