language: java
jdk:
- oraclejdk7
notifications:
  slack:
    secure: J5FTJJE9MPSLLcpHD/x93ZMwmsnz1ObxwWwgCvH2JGLEdKOkX/x7TbWesX5ni1SkExCiE1CZwdQ2hV5PlQmVvsTGXr9un0+kbKn3btmpsu2ITcoqVuxNUQbRDy0J3jiJhI3GwmbHdkffElVCQ1V6IUj1DPn8xOJbryFX85myego=
