sudo:required

language: java

jdk:
- openjdk8

services:
  - docker

before_script:
  - '[ "${TRAVIS_NODE_VERSION}" != "0.8" ] || npm install -g npm@1.4.28'
  - npm install -g npm@latest
  - npm --prefix src/main/web/florence install --unsafe-perm

after_success:
  - docker build -t carboni/florence:$TRAVIS_BRANCH .
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push carboni/florence:$TRAVIS_BRANCH

#script:
#  - npm --prefix src/main/web/florence/ test
