export const LOAD_POLICY_FAILURE = "LOAD_POLICY_FAILURE";
export const LOAD_POLICY_SUCCESS = "LOAD_POLICY_SUCCESS";
export const LOAD_POLICY_PROGRESS = "LOAD_POLICY_PROGRESS";

export const UPDATE_POLICY_FAILURE = "UPDATE_POLICY_FAILURE";
export const UPDATE_POLICY_SUCCESS = "UPDATE_POLICY_SUCCESS";
export const UPDATE_POLICY_PROGRESS = "UPDATE_POLICY_PROGRESS";
