export const UPDATE_ACTIVE_COLLECTION = "UPDATE_ACTIVE_COLLECTION";
export const EMPTY_ACTIVE_COLLECTION = "EMPTY_ACTIVE_COLLECTION";
export const MARK_COLLECTION_FOR_DELETE = "MARK_COLLECTION_FOR_DELETE";
export const DELETE_COLLECTION = "DELETE_COLLECTION";
export const UPDATE_PAGES_IN_ACTIVE_COLLECTION = "UPDATE_PAGES_IN_ACTIVE_COLLECTION";
export const UPDATE_TEAMS_IN_ACTIVE_COLLECTION = "UPDATE_TEAMS_IN_ACTIVE_COLLECTION";

export const LOAD_COLLECTIONS_PROGRESS = "LOAD_COLLECTIONS_PROGRESS";
export const LOAD_COLLECTIONS_SUCCESS = "LOAD_COLLECTIONS_SUCCESS";
export const LOAD_COLLECTIONS_FAILURE = "LOAD_COLLECTIONS_FAILURE";
