export const USER_LOGGED_OUT = "USER_LOGGED_OUT";
export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const START_REFRESH_AND_SESSION = "START_REFRESH_AND_SESSION";
export const END_REFRESH_SESSION = "END_REFRESH_SESSION";
export const END_SESSION_SESSION = "END_SESSION_SESSION";
