const USER_LOGGED_OUT = "USER_LOGGED_OUT";
const USER_LOGGED_IN = "USER_LOGGED_IN";
const START_REFRESH_AND_SESSION = "START_REFRESH_AND_SESSION";
const END_REFRESH_SESSION = "END_REFRESH_SESSION";
const END_SESSION_SESSION = "END_SESSION_SESSION";

export default {
    USER_LOGGED_OUT,
    USER_LOGGED_IN,
    START_REFRESH_AND_SESSION,
    END_REFRESH_SESSION,
    END_SESSION_SESSION,
};
