// Code generated by go-bindata.
// sources:
// ../dist/css/main.css
// ../dist/img/sprite.png
// ../dist/js/florence.bundle.js
// ../dist/legacy-assets/css/main.min.css
// ../dist/legacy-assets/index.html
// ../dist/legacy-assets/jquery.min.js
// ../dist/legacy-assets/js/main.js
// ../dist/legacy-assets/js/templates.js
// ../dist/legacy-assets/version.json
// ../dist/manifest.json
// ../dist/refactored.html
// ../dist/service-worker.js
// DO NOT EDIT!

package assets

import (
	"fmt"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
)

// bindataRead reads the given file from disk. It returns an error on failure.
func bindataRead(path, name string) ([]byte, error) {
	buf, err := ioutil.ReadFile(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset %s at %s: %v", name, path, err)
	}
	return buf, err
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

// DistCssMainCss reads file data from disk. It returns an error on failure.
func DistCssMainCss() (*asset, error) {
	path := "/Users/crispinmerriman/Dev/src/github.com/ONSdigital/florence/dist/css/main.css"
	name := "../dist/css/main.css"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// DistImgSpritePng reads file data from disk. It returns an error on failure.
func DistImgSpritePng() (*asset, error) {
	path := "/Users/crispinmerriman/Dev/src/github.com/ONSdigital/florence/dist/img/sprite.png"
	name := "../dist/img/sprite.png"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// DistJsFlorenceBundleJs reads file data from disk. It returns an error on failure.
func DistJsFlorenceBundleJs() (*asset, error) {
	path := "/Users/crispinmerriman/Dev/src/github.com/ONSdigital/florence/dist/js/florence.bundle.js"
	name := "../dist/js/florence.bundle.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// DistLegacyAssetsCssMainMinCss reads file data from disk. It returns an error on failure.
func DistLegacyAssetsCssMainMinCss() (*asset, error) {
	path := "/Users/crispinmerriman/Dev/src/github.com/ONSdigital/florence/dist/legacy-assets/css/main.min.css"
	name := "../dist/legacy-assets/css/main.min.css"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// DistLegacyAssetsIndexHtml reads file data from disk. It returns an error on failure.
func DistLegacyAssetsIndexHtml() (*asset, error) {
	path := "/Users/crispinmerriman/Dev/src/github.com/ONSdigital/florence/dist/legacy-assets/index.html"
	name := "../dist/legacy-assets/index.html"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// DistLegacyAssetsJqueryMinJs reads file data from disk. It returns an error on failure.
func DistLegacyAssetsJqueryMinJs() (*asset, error) {
	path := "/Users/crispinmerriman/Dev/src/github.com/ONSdigital/florence/dist/legacy-assets/jquery.min.js"
	name := "../dist/legacy-assets/jquery.min.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// DistLegacyAssetsJsMainJs reads file data from disk. It returns an error on failure.
func DistLegacyAssetsJsMainJs() (*asset, error) {
	path := "/Users/crispinmerriman/Dev/src/github.com/ONSdigital/florence/dist/legacy-assets/js/main.js"
	name := "../dist/legacy-assets/js/main.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// DistLegacyAssetsJsTemplatesJs reads file data from disk. It returns an error on failure.
func DistLegacyAssetsJsTemplatesJs() (*asset, error) {
	path := "/Users/crispinmerriman/Dev/src/github.com/ONSdigital/florence/dist/legacy-assets/js/templates.js"
	name := "../dist/legacy-assets/js/templates.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// DistLegacyAssetsVersionJson reads file data from disk. It returns an error on failure.
func DistLegacyAssetsVersionJson() (*asset, error) {
	path := "/Users/crispinmerriman/Dev/src/github.com/ONSdigital/florence/dist/legacy-assets/version.json"
	name := "../dist/legacy-assets/version.json"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// DistManifestJson reads file data from disk. It returns an error on failure.
func DistManifestJson() (*asset, error) {
	path := "/Users/crispinmerriman/Dev/src/github.com/ONSdigital/florence/dist/manifest.json"
	name := "../dist/manifest.json"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// DistRefactoredHtml reads file data from disk. It returns an error on failure.
func DistRefactoredHtml() (*asset, error) {
	path := "/Users/crispinmerriman/Dev/src/github.com/ONSdigital/florence/dist/refactored.html"
	name := "../dist/refactored.html"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// DistServiceWorkerJs reads file data from disk. It returns an error on failure.
func DistServiceWorkerJs() (*asset, error) {
	path := "/Users/crispinmerriman/Dev/src/github.com/ONSdigital/florence/dist/service-worker.js"
	name := "../dist/service-worker.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"../dist/css/main.css": DistCssMainCss,
	"../dist/img/sprite.png": DistImgSpritePng,
	"../dist/js/florence.bundle.js": DistJsFlorenceBundleJs,
	"../dist/legacy-assets/css/main.min.css": DistLegacyAssetsCssMainMinCss,
	"../dist/legacy-assets/index.html": DistLegacyAssetsIndexHtml,
	"../dist/legacy-assets/jquery.min.js": DistLegacyAssetsJqueryMinJs,
	"../dist/legacy-assets/js/main.js": DistLegacyAssetsJsMainJs,
	"../dist/legacy-assets/js/templates.js": DistLegacyAssetsJsTemplatesJs,
	"../dist/legacy-assets/version.json": DistLegacyAssetsVersionJson,
	"../dist/manifest.json": DistManifestJson,
	"../dist/refactored.html": DistRefactoredHtml,
	"../dist/service-worker.js": DistServiceWorkerJs,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"..": &bintree{nil, map[string]*bintree{
		"dist": &bintree{nil, map[string]*bintree{
			"css": &bintree{nil, map[string]*bintree{
				"main.css": &bintree{DistCssMainCss, map[string]*bintree{}},
			}},
			"img": &bintree{nil, map[string]*bintree{
				"sprite.png": &bintree{DistImgSpritePng, map[string]*bintree{}},
			}},
			"js": &bintree{nil, map[string]*bintree{
				"florence.bundle.js": &bintree{DistJsFlorenceBundleJs, map[string]*bintree{}},
			}},
			"legacy-assets": &bintree{nil, map[string]*bintree{
				"css": &bintree{nil, map[string]*bintree{
					"main.min.css": &bintree{DistLegacyAssetsCssMainMinCss, map[string]*bintree{}},
				}},
				"index.html": &bintree{DistLegacyAssetsIndexHtml, map[string]*bintree{}},
				"jquery.min.js": &bintree{DistLegacyAssetsJqueryMinJs, map[string]*bintree{}},
				"js": &bintree{nil, map[string]*bintree{
					"main.js": &bintree{DistLegacyAssetsJsMainJs, map[string]*bintree{}},
					"templates.js": &bintree{DistLegacyAssetsJsTemplatesJs, map[string]*bintree{}},
				}},
				"version.json": &bintree{DistLegacyAssetsVersionJson, map[string]*bintree{}},
			}},
			"manifest.json": &bintree{DistManifestJson, map[string]*bintree{}},
			"refactored.html": &bintree{DistRefactoredHtml, map[string]*bintree{}},
			"service-worker.js": &bintree{DistServiceWorkerJs, map[string]*bintree{}},
		}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

