---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: onsdigital/dp-concourse-tools-node-go

inputs:
  - name: florence
    path: florence

outputs:
  - name: build

run:
  path: florence/ci/scripts/build.sh
