---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: onsdigital/dp-concourse-tools-node-go
    tag: 1.23.4-bullseye-node-20

inputs:
  - name: florence
    path: florence

outputs:
  - name: build

caches:
  - path: go/
  - path: florence/node_modules

run:
  path: florence/ci/scripts/build.sh
