---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.8.3

inputs:
  - name: florence
    path: go/src/github.com/ONSdigital/florence

outputs:
  - name: build

run:
  path: go/src/github.com/ONSdigital/florence/ci/scripts/build.sh
