export const SET_CONFIG = "SET_CONFIG";

export const ADD_ALL_COLLECTIONS = "ADD_ALL_COLLECTIONS";

export const SEARCH = "SEARCH";
export const LOAD_COLLECTIONS_FAILURE = "LOAD_COLLECTIONS_FAILURE";
export const LOAD_COLLECTIONS_SUCCESS = "LOAD_COLLECTIONS_SUCCESS";
export const LOAD_COLLECTIONS_PROGRESS = "LOAD_COLLECTIONS_PROGRESS";

export const CREATE_COLLECTION_FAILURE = "CREATE_COLLECTION_FAILURE";
export const CREATE_COLLECTION_SUCCESS = "CREATE_COLLECTION_SUCCESS";
export const CREATE_COLLECTION_PROGRESS = "CREATE_COLLECTION_PROGRESS";

export const UPDATE_COLLECTION_FAILURE = "UPDATE_COLLECTION_FAILURE";
export const UPDATE_COLLECTION_SUCCESS = "UPDATE_COLLECTION_SUCCESS";
export const UPDATE_COLLECTION_PROGRESS = "UPDATE_COLLECTION_PROGRESS";

export const MARK_COLLECTION_FOR_DELETE_FROM_ALL_COLLECTIONS = "MARK_COLLECTION_FOR_DELETE_FROM_ALL_COLLECTIONS";
export const DELETE_COLLECTION_FROM_ALL_COLLECTIONS = "DELETE_COLLECTION_FROM_ALL_COLLECTIONS";
export const UPDATE_ACTIVE_COLLECTION = "UPDATE_ACTIVE_COLLECTION";
export const RESET = "RESET";

export const UPDATE_PAGES_IN_ACTIVE_COLLECTION = "UPDATE_PAGES_IN_ACTIVE_COLLECTION";
export const UPDATE_TEAMS_IN_ACTIVE_COLLECTION = "UPDATE_TEAMS_IN_ACTIVE_COLLECTION";
export const EMPTY_ACTIVE_COLLECTION = "EMPTY_ACTIVE_COLLECTION";

export const UPDATE_WORKING_ON = "UPDATE_WORKING_ON";
export const EMPTY_WORKING_ON = "EMPTY_WORKING_ON";

export const UPDATE_ACTIVE_USER = "UPDATE_ACTIVE_USER";
export const ADD_ALL_USERS = "ADD_ALL_USERS";
export const REMOVE_USER_FROM_ALL_USERS = "REMOVE_USER_FROM_ALL_USERS";

export const UPDATE_ALL_TEAMS = "UPDATE_ALL_TEAMS";
export const UPDATE_ALL_TEAMS_PROGRESS = "UPDATE_ALL_TEAMS_PROGRESS";
export const UPDATE_ALL_TEAMS_FAILURE = "UPDATE_ALL_TEAMS_FAILURE";
export const UPDATE_ACTIVE_TEAM = "UPDATE_ACTIVE_TEAM";
export const UPDATE_ACTIVE_TEAM_MEMBERS = "UPDATE_ACTIVE_TEAM_MEMBERS";

export const UPDATE_ALL_DATASETS = "UPDATE_ALL_DATASETS";
export const UPDATE_ACTIVE_DATASET = "UPDATE_ACTIVE_DATASET";
export const EMPTY_ACTIVE_DATASET = "EMPTY_ACTIVE_DATASET";
export const UPDATE_ACTIVE_DATASET_REVIEW_STATE = "UPDATE_ACTIVE_DATASET_REVIEW_STATE";
export const UPDATE_ACTIVE_DATASET_COLLECTION_ID = "UPDATE_ACTIVE_DATASET_COLLECTION_ID";
export const UPDATE_ALL_RECIPES = "UPDATE_ALL_RECIPES";
export const UPDATE_ALL_JOBS = "UPDATE_ALL_JOBS";
export const UPDATE_ACTIVE_JOB = "UPDATE_ACTIVE_JOB";
export const ADD_NEW_JOB = "ADD_NEW_JOB";
export const UPDATE_ACTIVE_INSTANCE = "UPDATE_ACTIVE_INSTANCE";
export const UPDATE_ACTIVE_VERSION_REVIEW_STATE = "UPDATE_ACTIVE_VERSION_REVIEW_STATE";
export const EMPTY_ACTIVE_INSTANCE = "EMPTY_ACTIVE_INSTANCE";
export const UPDATE_ACTIVE_VERSION = "UPDATE_ACTIVE_VERSION";
export const EMPTY_ACTIVE_VERSION = "EMPTY_ACTIVE_VERSION";

export const ADD_NOTIFICATION = "ADD_NOTIFICATION";
export const REMOVE_NOTIFICATION = "REMOVE_NOTIFICATION";
export const TOGGLE_NOTIFICATION_VISIBILITY = "TOGGLE_NOTIFICATION_VISIBILITY";

export const ADD_POPOUT = "ADD_POPOUT";
export const REMOVE_POPOUTS = "REMOVE_POPOUTS";

export const ADD_PREVIEW_COLLECTION = "ADD_PREVIEW_COLLECTION";
export const REMOVE_PREVIEW_COLLECTION = "REMOVE_PREVIEW_COLLECTION";
export const UPDATE_PREVIEW_SELECTED_PAGE = "UPDATE_PREVIEW_SELECTED_PAGE";
export const REMOVE_PREVIEW_SELECTED_PAGE = "REMOVE_PREVIEW_SELECTED_PAGE";
