export const initialState = {
    collections: {
        all: [],
        active: null,
        toDelete: {},
        isLoading: false,
        isUpdating: false,
    },
    config: {
        enableDatasetImport: false,
        enableNewSignIn: false,
        enableNewUpload: false,
        enablePermissionsAPI: false,
    },
    global: {
        workingOn: null,
    },
    rootPath: "/florence",
    teams: {
        active: {},
        all: [],
        users: [],
        isLoading: false,
    },
    users: {
        active: {},
        all: [],
        isAdding: false,
        isLoading: false,
        isUpdating: false,
        previewUsers: [],
        isLoadingActive: false,
        isRemovingAllTokens: false,
    },
    user: {
        data: null,
        groups: [],
        isLoading: false,
    },
    groups: {
        active: null,
        all: [],
        isLoading: false,
        isDeleting: false,
        members: [],
        isLoadingMembers: false,
    },
    datasets: {
        all: [],
        jobs: [],
        activeInstance: {},
        recipes: [],
        activeJob: {},
    },
    isUserAddingToGroups: false,
    search: "",
    notifications: [],
    popouts: [],
    preview: {
        selectedPage: null,
    },
    interactives: {
        all: [],
    },
    previewLanguage: "en",
};
