// Interactives
export const FETCH_INTERACTIVES = "FETCH_INTERACTIVES";
export const STORE_INTERACTIVE = "STORE_INTERACTIVE";
export const GET_INTERACTIVE = "GET_INTERACTIVE";
export const UPDATE_INTERACTIVE = "UPDATE_INTERACTIVE";

export const SORT_INTERACTIVES = "SORT_INTERACTIVES";

export const INTERACTIVE_ERROR = "INTERACTIVE_ERROR";
export const INTERACTIVE_RESET_ERROR = "INTERACTIVE_RESET_ERROR";
export const INTERACTIVE_SUCCESS = "INTERACTIVE_SUCCESS";
export const INTERACTIVE_RESET_SUCCESS = "INTERACTIVE_RESET_SUCCESS";

// Taxonomies
export const FETCH_TAXONOMIES = "FETCH_TAXONOMIES";
export const TAXONOMY_ERROR = "TAXONOMY_ERROR";
