export const FETCH_INTERACTIVES = "FETCH_INTERACTIVES";
export const STORE_INTERACTIVE = "STORE_INTERACTIVE";
export const GET_INTERACTIVE = "GET_INTERACTIVE";
export const UPDATE_INTERACTIVE = "UPDATE_INTERACTIVE";
export const INTERACTIVE_ERROR = "INTERACTIVE_ERROR";